### ISSUE TITLE
Repo names are not actually supported as an image id

### ISSUE THREAD

**Issue by dustyhorizon** [anchore/anchore#30]
Under `anchore query --extended-help` it is said that Image IDs can be specified as repo names

However, after analyzing a bunch of my private images using `anchore analyze --image <repo>/<image>`, `anchore query --image <repo> cve-scan all` returns `ERROR could not load input images: Input image name <repo> not found in local dockerhost or anchore DB.`

My aim is to be able to query / audit all images from a specific repo as part of a workflow process. There may be other images present in docker that I do not intend to analyze.

On a side note, is there a way to easily reset the anchore db / remove all analyzed images instead of `rm -rf ~/.anchore`?

**Comment by acathrow** [comment]
Today you need to _docker _pull__ the image before the anchore cli will analyze it.
Once analyzed the image can be deleted however we then lose the mapping of repo/image to tag.
So for example after analyzing alpine:latest I can _docker rmi alpine:latest_ and still run queries on the image but I'd have to use the imageid rather than the repo/name which is inconvenient.

The plan is to move to a more service based model where Anchore is run in a container and accessed through REST API and CLI to issues the analyze/gate/etc commands which probably simplify what you're trying to do, although you can automate this today scripting anchore and docker commands, it's just not out of the box.


In terms of the database pruning, you can remove individual images using
`anchore toolbox --image=foo/bar delete`
and can get a list of images in the database using
`anchore toolbox images`

**Comment by dustyhorizon** [comment]
Ah I see, was confused by the output of `anchore query --extended-help`:

```
[trunc]
Image IDs can be specified as hash ids, repo names (e.g. centos), or tags (e.g. centos:latest).
[trunc]
```

Being able to generate a report based on repo name / multiple images (without recusively selecting individual images, generate the report then append the output to some file) would be a great addition to this tool I would think. Thanks for the clarification too!
