### ISSUE TITLE
Dockerfile does not exist

### ISSUE THREAD

**Issue by sammcj** [anchore/anchore#37]
If you follow the readme instructions for running anchore from a Docker image then using docker exec to call anchore analyze as it suggests the command fails.

I believe this is because the command is looking for a Dockerfile within the running Docker container rather than on the hosts filesystem tree:

As you can see the Dockerfile exists and is in the path provided below as per the readme instructions:
```
ls -l /Users/samm/git/docker-base-image/Dockerfile
```

However, when called even with the fully qualified path the command files:
```
docker exec anchore anchore analyze --image 58329f1f1727 --dockerfile /Users/samm/git/docker-base-image/Dockerfile
Usage: anchore analyze [OPTIONS]

Error: Invalid value for "--dockerfile": Path "/Users/samm/git/docker-base-image/Dockerfile" does not exist.
```

- Docker version 17.07.0-ce-rc1, build 8c4be39
- MacOS 10.12.6

**Comment by acathrow** [comment]
Because the exec runs from outside the container anything involving a file such as --editpolicy or passing a dockerfile will see this behaviour.
One quick way around this it to mount a volume into the container -v /Users/sam/git/:/Users/sam/git:ro  or to copy the file into the container and run the command inside the container.
Neither are elegant solutions which is why we're moving to a service based approach with the docker image provides a RESTful interface that you can interact with either directly or through a  CLI.
We are planning on open sourcing this and pushing it out later this month but if you're interesting in doing some early testing please reach out to me andrew@cathrow.com

**Comment by sammcj** [comment]
I suspected that was indeed the cast.

Fantastic - thank you for the offer - I've just dropped you an email :)
